name: DragonsContentTools
main: mc.dragons.tools.content.DragonsContentTools
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
api-version: 1.16
description: Provides tools for GMs to view and edit game data.
commands:
  clear:
    description: (TESTER) Clear your inventory.
  floor:
    description: (GM) Manage floors.
  gamemode:
    aliases: gm
    description: (BUILDER) Change your gamemode.
  gmc:
    description: (BUILDER) Alias for /gamemode creative
  gms:
    description: (BUILDER) Alias for /gamemode survival
  gma:
    description: (BUILDER) Alias for /gammemode adventure
  gotofloor:
    description: (BUILDER) Go to the specified floor.
  item:
    aliases: i
    description: (GM) Manage items and item classes.
  npc:
    description: (GM) Manage NPCs and NPC classes.
  quest:
    aliases: q
    description: (GM) Manage quests.
  region:
    description: (GM) Manage regions.
  relore:
    description: (GM) Edit lore of your held item.
  rename:
    description: (GM) Edit the name of your held item.
  restat:
    description: (GM) Edit the statistics of your held item.
  speed:
    description: (BUILDER) Set your walk or fly speed.
  flyspeed:
    description: (BUILDER) Alias for /speed fly.
    aliases: fs
  walkspeed:
    description: (BUILDER) Alias for /speed walk.
    aliases: ws
  testquest:
    description: (TESTER) Start any quest or jump to a specific stage.
  updatestats:
    description: (GM) Update a player's statistics.
  warp:
    description: (BUILDER) Teleport to the specified warp point.
  warps:
    description: (BUILDER) List all warp points.
  setwarp:
    description: (BUILDER) Add a warp point at your specified location.
  delwarp:
    description: (BUILDER) Delete a warp point.
  resetprofile:
    description: (TESTER) Reset your game statistics. Punishment and IP history are not affected.
    aliases: statswipe
  placeholder:
    description: (GM) Set a placeholder which can be used in lengthy content commands.
    aliases: ph
  fixed:
    description: (BUILDER) Sets the targeted entity to stay in place and persist past server restarts.
  objmeta:
    description: (GM) View metadata about a game object.
  deletenpc:
    description: Internal command!
  hologram:
    description: (GM) Create and manage standalone holograms.
    aliases: [holo, h]
