#
# Configuration file for Dragons Online.
#

# Dragons Online requires a connection to a MongoDB database server.
db:
  mongo:
    host: localhost
    port: 27017
    user: root
    password: password
    auth_db: admin
    database: dragons
    password-salt-string: 'replace this with your unique salt string'
    
    # Global variables are configuration data shared between servers.
    # You can specify different, independent clusters of global variables
    # by giving them unique accession tokens.
    global-var-accession-token: 'replace this with a string identifying the global variable document to use'

# The name of this server instance.
serverName: dragons-1

# When in debug mode, game integrity is not verified and the log level
# is set to CONFIG if the default setting is higher than this.
debug: false

# The default level at which the logger outputs.
# Valid levels are OFF, SEVERE, WARNING, NOTICE, INFO, CONFIG, DEBUG, TRACE, VERBOSE, ALL
# FINE, FINER, and FINEST are also valid but discouraged because they're arbitrary.
loglevel: INFO

# Custom log output format to the console.
# Placeholders:
#   %t      time HH:mm:ss
#   %d      date yyyy-MM-dd
#   %j      thread name
#   %l      log level
#   %s      logger name
#   %m      log message
log-format:
  with-logger: '[%t %j/%l] [%s] %m'
  without-logger: '[%t %j/%l] %m'
  
  # Logger names over 20 characters will be truncated
  truncate-logger-names: true
  
  # Certain loggers, such as CraftBukkit and NMS, are further abbreviated for readability
  special-logger-names: true
  
  # Thread names over 30 characters will be truncated
  truncate-thread-names: true
  
  # Log messages internal to Minecraft will be displayed as if from an empty logger
  anonymize-minecraft-internal: true

# Settings related to in-game functionality.
game:
  # Use %SERVER% as a placeholder for the player's current server.
  tablist:
    header: '&8- &5&lDragons &f&lOnline &8-'
    footer: '&7You are currently connected to %SERVER%'
