name: DragonsCore
main: mc.dragons.core.Dragons
version: 1.0.0
author: DragonRider747
depend: [ProtocolLib]
loadbefore: [WorldEdit, Builders-Utilities]
load: POSTWORLD
api-version: 1.16
description: Provides core APIs and game object functionality.
commands:
  dragons:
    description: (ADMIN) View Dragons status.
  fastforwarddialogue:
    description: Fast-forward through active quest dialogue.
  feedback:
    description: Send feedback about DragonsOnline.
  help:
    description: Halp
    aliases: '?'
  myquests:
    description: List your active quests.
  news:
    description: View unread changelogs and announcements.
    aliases: whatsnew
  questchoice:
  syslogon:
    description: Log on to the system console.
  stuckquest:
    description: Report a problem with a quest.
    aliases: [brokenquest, reportquest]
  respawn:
    description: (TESTER) Skip the death countdown and respawn instantly.
  heal:
    description: (MOD) Heal yourself or another player.
  getstate:
    description: (MOD) Get a state token from the specified player.
  setstate:
    description: (MOD) Set your state to the specified state token.
  newsmanager:
    description: (GM) Manage announcements and changelogs.
  rank:
    description: (ADMIN) Set a player's rank.
  autorank:
    description: (ADMIN) Set the default rank for the specified player when they first join.
  restartinstance:
    description: (ADMIN) Restart the specified server instance.
