name: DragonsSpells
main: mc.dragons.spells.DragonsSpells
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
api-version: 1.16
description: Implements spells, a series of addons that allow custom actions to be bound to item classes.
commands:
  bindspell:
    description: (GM) Bind a spell to your held item.
  testspellbinding:
