# The URL of the webhook used to send Discord notifications.
discord-notifier-webhook-url: 'https://discord.com/api/webhooks/webhook-id-goes-here'

# The role ID for builders.
roleid-builder: '&1234567890'

# The role ID for task managers.
roleid-tm: '&1234567890'

# The role ID for developers.
roleid-dev: '&1234567890'

# The role ID for game masters.
roleid-gm: '&1234567890'

# Whether to enable sending Discord notifications.
discord-notifier-enabled: true

# Staff advice settings
staff-advice:
  period-seconds: 120
  
# World backup settings
backup:
  # Root folder to which backups are saved.
  folder: 'C:\\DragonsBackups\\'
  
  # How frequently backups are made.
  period-minutes: 60
  
  # How long backups are kept before being deleted.
  # Set to -1 to keep backups indefinitely.
  retention-days: 30

stars:
  # How many stars can a task have at most?
  max-per-task: 5
  
  # How many stars can a player stand to gain at any
  # one time from their assigned tasks?
  max-assign-stars: 10

  # Items that staff can buy with stars
  staff-shop:
    # ItemClassName: PriceInStars
