name: DragonsDev
main: mc.dragons.dev.DragonsDevPlugin
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
api-version: 1.16
commands:
  starttrial:
    description: Create a build trial for the specified player.
  task:
    description: Create a task.
  taskloc:
    description: Change the location of a task.
  tasknote:
    description: Add a note to a task.
  gototask:
    description: Teleport to a task.
  tasks:
    description: List active tasks.
  taskinfo:
    description: Information about the specified task.
  assign:
    description: Assign a player to a task.
  done:
    description: Mark a task as completed.
  close:
    description: Close a completed task.
  approve:
    description: Approve a task.
  reject:
    description: Reject a task.
  deletetask:
    description: Delete a task.
  backup:
    description: (BUILDER) Force a backup of the server floor worlds.
  togglediscordnotifier:
    description: (ADMIN) Toggle discord notifications for tasks.
  discordnotifyraw:
    description: (ADMIN) Send a message directly through the discord notifier.
  tips:
    description: Toggle staff tips on or off.
  taskhelp:
    description: View commands for tasks.
