name: DragonsDevTools
main: mc.dragons.tools.dev.DragonsDevTools
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore, ProtocolLib]
api-version: 1.16
description: Utilities for developers to monitor, debug, test, and reconfigure the server.
commands:
  addon:
    description: (ADMIN) Manage item and NPC addons.
  autosave:
    description: (ADMIN) Auto-save all eligible game objects immediately.
  correlation:
    description: (ADMIN) Search log entries by correlation ID and level.
  debug:
    description: (ADMIN) Access debug tools.
  lag:
    description: Analyze recent performance data for possible issues.
  loglevel:
    description: (ADMIN) Change the console log level.
  ping:
    description: View a player's ping, in milliseconds.
  reloadquests:
    description: (ADMIN) Reload all quests from the database.
  serveroptions:
    description: (ADMIN) Change active configuration data.
  serverperformance:
    description: (ADMIN) View aggregated performance statistics about the server.
  getprocessid:
    description: (ADMIN) View the current process ID of the server.
  killtask:
    description: (ADMIN) Immediately cancel a running Bukkit task.
  killtasks:
    description: (ADMIN) Immediately cancel all running Bukkit tasks.
  killtasksfor:
    description: (ADMIN) Immediately cancel all running Bukkit tasks of the specified plugin.
  crashserver:
    description: (ADMIN) Immediately crash the server, without data saving.
  generatedump:
    description: (ADMIN) Dump data about the current server state, including game objects and performance.
  requestgc:
    description: (ADMIN) Request garbage collection by the JVM. Behavior is platform-dependent and configuration-dependent.
  enableplugin:
    description: (ADMIN) Enable a plugin that has been disabled.
  disableplugin:
    description: (ADMIN) Disable a plugin. Associated tasks may or may not be cancelled.
  ilikevanilla:
    description: (ADMIN) Replicate vanilla functionality by disabling all plugins.
  invalidate:
    description: (ADMIN) Remove a specified game object from the cache.
  invalidateall:
    description: (ADMIN) Remove all game objects from the cache.
  invalidatetype:
    description: (ADMIN) Remove all game objects of a given type from the cache.
  invalidateuser:
    description: (ADMIN) Remove a given player from the cache.
  localize:
    description: (ADMIN) Disconnect a specified game object from the database. It will not be deleted, but future local changes will not be persisted until a restart.
  localizeall:
    description: (ADMIN) Disconnect all game objects from the database. They will not be deleted, but future local changes will not be persisted until a restart.
  localizetype:
    description: (ADMIN) Disconnect all game objects of a given type from the database. They will not be deleted, but future local changes will not be persisted until a restart.
  localizeuser:
    description: (ADMIN) Disconnect the specified player from the database. They will not be deleted, but future local changes will not be persisted until a restart.
  verifygameintegrity:
    description: (ADMIN) Scan game objects and caches for inconsistencies and attempt to resolve them if the -resolve flag is specified.
  worldperformance:
    description: (ADMIN) View performance statistics broken down by world.
  worldmanager:
    description: (ADMIN) Manage settings for a given world.
  unloadchunks:
    description: (ADMIN) Unload all chunks that can be unloaded for a given world.
  reloadchunks:
    description: (ADMIN) Unload and reload all chunks that can be unloaded for a given world.
  cleardrops:
    description: (ADMIN) Clear all dropped items in a given world.
  clearmobs:
    descripton: (ADMIN) Clear all non-persistent mobs in a given world.
  helditemdata:
    aliases: whatamiholding
    description: (ADMIN) View data about the item you are holding.
  rawtext:
    description: (ADMIN) Display raw text, formatted with color codes.
  whoami:
    description: (ADMIN) View your associated game object entry.
  stresstest:
    description: (ADMIN) Spawn a large number of entities on the same tick.
  killmobs:
    description: (ADMIN) Kill all entities.
  testexceptions:
  testmineregen:
  testpermission:
    description: (ADMIN) Check if you have a particular Bukkit permission node.
  testlocaluserstorage:
  testgui:
  testhdfont:
  testtabname:
  testpathfinding:
  testphasing:
  testarmorstandpose:
  testtpsrecord:
  testleveling:
  testlogging:
  testuuidlookup:
  testnetworkmessage:
  mongo:
    description: (ADMIN) View data about the active MongoDB connection.
  panic:
    description: (ADMIN) Crash the server after dumping data about the current state.
  testcorrelationlogging:
  testbase64encoding:
  getservername:
    description: (ADMIN) View the name of the current server you're connected to.
  tickperformance:
    description: (ADMIN) Analyze tick-related performance data over the specified time interval.
    aliases: tickperf
  getstacktrace:
    description: (ADMIN) Get the stack trace of the current thread, or of the thread with the specified ID.
  getactivethreads:
    description: (ADMIN) List all currently running threads and their groups.
  getglobalaccessiontoken:
    description: (ADMIN) Displays the server instance's global variable accession token.
  setglobalaccessiontoken:
    description: (ADMIN) Changes the server instance's global variable accession token.
  getglobalvariables:
    description: (ADMIN) Displays all global variables.
  spoofserver:
    description: (ADMIN) Change your cached server.
  clearnetworkmessagecache:
    description: (ADMIN) Clear all network messaging data, optionally older than the specified time.
    aliases: clearnmc
  printnetworkmessages:
    description: (ADMIN) Toggle debug logging of network messages to console.
  manifest:
    description: (ADMIN) Display a manifest of all users connected to all servers.
  testdocumentdelta:
  getlogtoken:
    description: (ADMIN) Display the token to view this server's remote log entries.
  ignoreremoterestarts:
    description: (ADMIN) Toggle whether to ignore incoming remote restarts.
  vgir:
    description: (ADMIN) Shortcut for /verifygameintegrity -resolve
    aliases: vrgit
  testnewfonts:
  getnetworkstate:
    description: (ADMIN) Display data about the server's network connection.
  testuserlookup:
  getsystemproperties:
    description: (ADMIN) Display all JRE system properties.
  writelog:
    description: (ADMIN) Write directly to the server log.
  testheader:
  testfooter:
  streamconsole:
    description: (ADMIN) Receive console logs in the chat.
  resyncuserdata:
    description: (ADMIN) Resync all user data from the database. Some data caches may not be updated.
  testinvisibleslimes:
  testrevealslimes:
  testhideslimes:
  testdestroyslimes:
  testbadslimes:
  mockuser:
    description: (ADMIN) Create a fake user for testing.
  mocksudo:
    description: (ADMIN) Run a command as a fake user.
  mockinject:
    description: (ADMIN) Inject a fake user into the server registries after creating it.
  mockserver:
    description: (ADMIN) Spoof the server that a mock user is connected to.
  mockdelete:
    description: (ADMIN) Delete a mock user.
  mocklist:
    description: (ADMIN) List all mock users.
  mockuninject:
    description: (ADMIN) Un-inject a fake user locally without deleting them from the database.
  testitemstash:
  testitemunstash:
  testmobai:
  testtakeitem:
  testupdateinventory:
  testnametag:
  testnametag2:
  testupdatenametag:
  testrollingasync:
  testinternalnetworkedmsg:
  sudo:
    aliases: iwillnotabusethiscommand
  testplayernpc:
    aliases: npctool
  testrevealallinvisible:
  testinventoryreload:
  getitemuuid:
  tptoentity:
  dumpteams:
  lab:
  getprotocolversion:
  testtabsorting:
