name: DragonsDevTools
main: mc.dragons.tools.dev.DragonsDevToolsPlugin
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
commands:
  addon:
  debug:
  lag:
  loglevel:
  ping:
  placeholder:
  reloadquests:
  serveroptions:
  serverperformance:
  getprocessid:
  killtask:
  killtasks:
  killtasksfor:
  crashserver:
  generatedump:
  requestgc:
  enableplugin:
  disableplugin:
  ilikevanilla:
  invalidate:
  invalidateall:
  invalidatetype:
  invalidateuser:
  localize:
  localizeall:
  localizetype:
  localizeuser:
  verifygameintegrity:
  worldperformance:
  helditemdata:
    aliases: whatamiholding
  rawtext:
  whoami:
  stresstest:
  killmobs:
  testexceptions:
  testmineregen:
  testpermission:
  testlocaluserstorage:
  testgui:
  testhdfont:
  testtabname:
  testpathfinding:
  testphasing:
  testarmorstandpose:
  testleveling:
  testlogging:
  testuuidlookup:
  mongo:
  panic:
