name: DragonsModerationTools
main: mc.dragons.tools.moderation.DragonsModerationToolsPlugin
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
commands:
  escalate:
  report:
  chatreport:
  reports:
  viewreport:
    aliases: vr
  godmode:
  info:
  warn:
  kick:
  mute:
  ban:
  unmute:
  unban:
  removepunishment:
  viewpunishments:
  vanish:
    aliases: v
  unvanish:
    aliases: uv
  fly:
