name: DragonsSocial
main: mc.dragons.social.DragonsSocial
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
api-version: 1.16
description: Implements social functionality such as guilds and private messaging.
commands:
  guild:
    description: Create, join, and manage guilds.
    aliases: g
  guildadmin:
    description: (ADMIN) Manage guilds.
  chatspy:
    description: (MOD) View other players' private messages.
  shout:
    description: (MOD) Broadcast to the entire server.
    aliases: [broadcast, bc]    
  reply:
    description: Reply to your last incoming message.
    aliases: [r, re]
  party:
    description: Create, join, and manage parties.
    aliases: p
    description: Log on to system console.
  msg:
    description: Send a private message.
    aliases: [tell, t, m, pm, whisper, w]
    description: Send feedback about the game.
  friend:
    description: Make friends!
    aliases: f
  channel:
    description: Set speaking and listening chat channels.
    aliases: [c, ch, chat, csa, csl, csg, csp, cst, csh, css, cla, cll, clg, clp, clt, clh, cls]
  duel:
    description: Request to 1v1 a player.
  listallduelstatus:
    description: (ADMIN) List all pending or in-progress duels.
  testduelwin:
  toggleselfmessage:
    description: (ADMIN) Toggle your ability to message yourself. No other players are affected.
  block:
    description: Block chat messages, private messages, and friend requests from the specified player.
  unblock:
    description: Allow chat messages, private messages, and friend requests from the specified player.
  toggleselffriend:
    description: (ADMIN) Toggle your ability to friend-request yourself. No other players are affected.
  toggleselfblock:
    description: (ADMIN) Toggle your ability to block/unblock yourself. No other players are affected.
  togglemsg:
    description: Toggle whether you can be messaged by everyone or by friends only.
  toggleselfparty:
    description: (ADMIN) Toggle your ability to add yourself to a party. No other players are affected.
  dumpParties:
    description: (ADMIN) Dump diagnostic information about active parties.
  dumpFriends:
    description: (ADMIN) Dump diagnostic information about your friend status.
