#
# Configuration file for Dragons Online.
#

# Dragons Online requires a connection to a MongoDB database server.
db:
  mongo:
    host: localhost
    port: 27017
    user: root
    password: password
    auth_db: admin
    database: dragons
    password-salt-string: 'replace this with your unique salt string'
    
    # Global variables are configuration data shared between servers.
    # You can specify different, independent clusters of global variables
    # by giving them unique accession tokens.
    global-var-accession-token: 'replace this with a string identifying the global variable document to use'

# The name of this server instance.
serverName: dragons-1

# When in debug mode, game integrity is not verified and the log level
# is set to CONFIG if the default setting is higher than this.
debug: false

# The default level at which the logger outputs.
# Valid levels are OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
loglevel: INFO
