name: DragonsCore
main: mc.dragons.core.Dragons
version: 1.0.0
author: DragonRider747
depend: [ProtocolLib]
loadbefore: [WorldEdit]
load: POSTWORLD
commands:
  fastforwarddialogue:
    description: Fast-forward through active quest dialogue.
  feedback:
    description: Send feedback about DragonsOnline.
  help:
    description: Halp
    aliases: '?'
  myquests:
    description: List your active quests.
  news:
    description: View unread changelogs and announcements.
    aliases: whatsnew
  questchoice:
  syslogon:
    description: Log on to the system console.
  stuckquest:
    description: Report a problem with a quest.
    aliases: [brokenquest, reportquest]
  respawn:
    description: (TESTER) Skip the death countdown and respawn instantly.
  heal:
    description: (MODERATOR) Heal yourself or another player.
  newsmanager:
    description: (GM) Manage announcements and changelogs.
  rank:
    description: (ADMIN) Set a player's rank.