name: DragonsAntiCheat
main: mc.dragons.anticheat.DragonsAntiCheat
version: 1.0.0
author: DragonRider747
depend: [DragonsCore, DragonsModerationTools]
api-version: 1.16
description: (EXPERIMENTAL) Enforces vanilla gameplay behavior and detects illegal client modifications.
commands:
  ac:
  acdebug:
  acflushlog:
  acstartlog:
  acblockdata:
  acban:
  ackick:
  acdump:
  acresetplayer:
  acstatus:
  actoggle:
  acping:
  acspoofping:
  acraytol:
  acpps:
  achitstats:
  acresethitstats:
  actogglerewind:
