name: DragonsSocial
main: mc.dragons.social.DragonsSocialPlugin
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
commands:
  guild:
    description: Create, join, and manage guilds.
    aliases: g
  guildadmin:
    description: (ADMIN) Manage guilds.
  chatspy:
    description: (MOD) View other players' private messages.
  shout:
    description: (MOD) Broadcast to the entire server.
    aliases: [broadcast, bc]    
  reply:
    description: Reply to your last incoming message.
    aliases: [r, re]
  party:
    description: Create, join, and manage parties.
    aliases: p
    description: Log on to system console.
  msg:
    description: Send a private message.
    aliases: [tell, t, m, pm, whisper, w]
    description: Send feedback about the game.
  friend:
    description: Make friends!
    aliases: f
  channel:
    description: Set speaking and listening chat channels.
    aliases: [c, ch, chat]
  duel:
    description: Request to 1v1 a player.
  listallduelstatus:
    description: (ADMIN) List all pending or in-progress duels.
  testduelwin:
  toggleselfmessage:
    description: (ADMIN) Toggle your ability to message yourself. No other players are affected.
