name: DragonsModerationTools
main: mc.dragons.tools.moderation.DragonsModerationTools
version: 1.0.0
author: UniverseCraft
depend: [DragonsCore]
api-version: 1.16
description: Utilities for the moderation team to monitor and take action on user behavior.
commands:
  escalate:
    description: (HELPER) Escalate an issue with a player for action by senior staff.
  report:
    description: Report a rule-breaker.
  chatreport:
    description: Click on a message in chat to report it.
  reports:
    description: (MODERATOR) List reports by a variety of search criteria.
  viewreport:
    aliases: [vr, vrep]
    description: (MODERATOR) View and manage a report.
  godmode:
    description: (MODERATOR) Activate or deactivate invincibility status.
  info:
    description: (MODERATOR) View a summary of a player's data.
    aliases: userinfo
  iphistory:
    description: (ADMIN) View all IP addresses a player has used.
  ipscan:
    description: (MODERATOR) Search for alt accounts based on known IP.
  unmute:
    description: (MODERATOR) Unmute a player. The mute stays on the player's record.
  unban:
    description: (MODERATOR) Unban a player. The ban stays on the player's record.
  removepunishment:
    description: (ADMIN) Expunge a punishment from a player's record.
  setverification:
    description: (MODERATOR) Set a player's community verification status.
  viewpunishments:
    description: (MODERATOR) View a player's punishment records.
  vanish:
    description: (HELPER) Become invisible.
    aliases: [v, van]
  unvanish:
    description: (HELPER) Become visible.
    aliases: [uv, unvan]
  fly:
    description: (HELPER) Toggle survival-mode flying capability.
  toggleselfreport:
    description: (ADMIN) Toggle your ability to report yourself. Does not affect other players.
  deletereport:
    description: (ADMIN) Permanently delete a report from the database.
  locate:
    description: (HELPER) Find the server a player is connected to.
  modqueue:
    description: (MODERATOR) Get the next report to review.
    aliases: [modq, mq, nextreport, nr]
  modnotifications:
    description: (MODERATOR) Manage your moderation-related notification settings.
    aliases: [modnotifs, modn, mn]
  hold:
    description: (MODERATOR) Place a hold on one or more players
  punish:
    description: (HELPER) Apply a punishment to a player
  punishcodes:
    description: (HELPER) List all punishment codes
    aliases: pcodes
  setstandinglevel:
    description: (ADMIN) Change a player's standing level
    aliases: setsl
  purgepunishments:
    description: (ADMIN) Purge a player's punishment history

